# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pr:
- main

pool:
  name: 'aws1'

variables:
  solutionPath: 'src/Wpf.sln'

jobs:
- job: Build
  displayName: 'Build and Run'
  steps:
  - checkout: self
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 6.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions
  - script: dotnet restore $(solutionPath)
    displayName: 'Restore NuGet packages'
  - script: dotnet build --configuration Release $(solutionPath)
    displayName: 'Build the project'
  # - script: dotnet run --configuration Release --project ./src/WpfApp/WpfApp.csproj
  #   displayName: 'Build run'  
- job: Test
  dependsOn: Build
  displayName: 'Running test'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 6.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions
  - script: dotnet test --configuration Release --no-build $(solutionPath)
    displayName: 'Run tests'
    
- job: Deploy
  dependsOn: Test
  displayName: 'Deploy job'
  condition: succeeded()
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 6.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions
  - script: dotnet publish --configuration Release $(solutionPath)
    displayName: 'Deploy'
