trigger:
- main

pr:
- main

variables:
  solutionPath: 'src/Wpf.sln'

pool:
  name: 'gcp1'

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - checkout: self
  - task: UseDotNet@2
    inputs:
      version: '6.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: dotnet restore $(solutionPath)
    displayName: 'Restore NuGet packages'
  - script: dotnet build --configuration Release $(solutionPath)
    displayName: 'Build the project'
  - script: dotnet test --configuration Release --no-build $(solutionPath)
    displayName: 'Run tests'

- job: Deploy
  displayName: 'Deploy job'
  condition: succeeded()
  steps:
  - script: echo 'Deploying...'
    displayName: 'Deployment step'
