# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pr:
- main

pool:
  name: 'gcp1'

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - checkout: self
  - task: UseDotNet@2
    inputs:
      version: '6.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: dotnet restore
    displayName: 'Restore NuGet packages'
  - script: dotnet build --configuration Release
    displayName: 'Build the project'
  - script: dotnet test --configuration Release --no-build
    displayName: 'Run tests'

- job: Deploy
  displayName: 'Deploy job'
  condition: succeeded()
  steps:
  - script: echo 'Deploying...'
    displayName: 'Deployment step'

